### ISSUE TITLE
word constructor

### ISSUE THREAD

**Issue by LipSoft** [decisively/wink-porter2-stemmer#23]
on node using version "wink-porter2-stemmer": "^2.0.0"
this code 
```
const stem = require('wink-porter2-stemmer')
console.log(stem('constructor'))
```

`returns [Function: Object] `

instead of a string and stem('constructor')() returns an empty object {}

This is due to the fact you use an object for exceptions

`if ( exceptions1[ str ] ) return ( exceptions1[ str ] );`

and in javascript object['constructor'] will return a function if that key doesn't exists on the object

**Comment by sanjayaksaxena** [comment]
Hi @LipSoft 

Many thanks for highlighting the issue along with the details that we missed. Fixing it right away.

Best,
Sanjaya
