### ISSUE TITLE
review and setup nodesecurity.io

### ISSUE THREAD

**Issue by prtksxna** [decisively/wink-porter2-stemmer#3]

**Comment by prtksxna** [comment]
This will check for vulnerabilities and provide a badge like -   [![NSP Status](https://nodesecurity.io/orgs/decisively/projects/f18c9155-11fc-4b6c-b9aa-f3cce7c7dfb7/badge)](https://nodesecurity.io/orgs/decisively/projects/f18c9155-11fc-4b6c-b9aa-f3cce7c7dfb7)

Given that this package has **0** dependencies, and its unlikely that there would be a report specifically for **wink-porter2-stemmer** on NSP, I don't think it provides any useful information.

On the other hand, it might be good for trust?

**Comment by sanjayaksaxena** [comment]
Will review later
