### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by crystalfp** [decisively/wink-porter2-stemmer#36]
Could typescript declarations be provided for this module (and maybe all the modules of wink)?
Thanks!
mario

**Comment by prtksxna** [comment]
Hey @crystalfp! Thanks for that suggestion. 

Unfortunately, we aren't super familiar with Typescript or how we'd go about doing this. Would it mean [adding a .d.ts file](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) for each of the modules? Would we need to include any [Typescript related dependencies](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html)?

We'd be grateful if you could point us in the right direction. It'd help us figure out if we'd be able to prioritize this 🙂

**Comment by crystalfp** [comment]
Half success. 😞
I have created the file `node_modules/wink-porter2-stemmer/src/wink-porter2-stemmer.d.ts` containing the line `export declare function stem(input: string): string;`

In the code now I can `import stem from "wink-porter2-stemmer";` and call it as `const stemmed = stem(word);`

Unfortunately `eslint` continues to complain that: Unsafe assignment of an `any` value and Unsafe call of an `any` typed value.

**Comment by crystalfp** [comment]
Look at this [Stackoverflow question](https://stackoverflow.com/questions/67817679/how-to-import-in-ts-a-mature-library-that-exports-a-single-function) for my solution. The only recent change is about point 3 in which I called `(stem as (w: string) => string)(word);` And now no more complains by eslint! BTW, your library is not alone, I use few libraries for which I had to implement a variety of hacks to make typescript (and runtime) happy.

**Comment by crystalfp** [comment]
This seems to work, at last!
1) Under `node_modules/wink-porter2-stemmer/src` create the file `wink-porter2-stemmer.d.ts` containing the single line `export function stem(term: string): string;`
2) In the source import your stemmer with `import {stem} from "wink-porter2-stemmer";`
3) Use it as `stem("president")`
Please do your testing then, if possible, release a version of the package so I could remove my "illegal" addition under node_modules. Thanks!

**Comment by crystalfp** [comment]
Sorry for all the noise, but the above solution should be changed to this:

1. Under `node_modules/wink-porter2-stemmer/src` create the file `wink-porter2-stemmer.d.ts` containing:
```
declare module "wink-porter2-stemmer";
export default function stem(term: string): string;
```
2. In the source import your stemmer with `import stem from "wink-porter2-stemmer";`
3. Use it as `stem("president")`

At last this compiles and works. The one before crashed at runtime. Why it had worked for a while, I don't know.
